// MaxCred fee-aware demo engine — verified launch dataset.
(function(){
const C=window.MAXCRED_CARDS||[],GST=.18,m=n=>'₹'+Math.round(Math.max(0,n)).toLocaleString('en-IN');
function spend(){const s={};document.querySelectorAll('.spend').forEach(r=>{const l=(r.querySelector('label')?.textContent||'').toLowerCase(),v=Number(r.querySelector('input')?.value||0);let k='other';if(l.includes('airtel'))k='airtel';else if(l.includes('utility')||l.includes('bill'))k='utilities';else if(l.includes('online')||l.includes('shopping'))k='online';else if(l.includes('travel'))k='travel';else if(l.includes('fuel'))k='fuel';else if(l.includes('dining'))k='dining';else if(l.includes('rent'))k='rent';else if(l.includes('wallet'))k='wallet';else if(l.includes('upi'))k='upi';s[k]=(s[k]||0)+v});return s}
function eligible(c,s){let t=Object.values(s).reduce((a,b)=>a+b,0)*12;if(c.id==='axis-cashback')t-=((s.rent||0)+(s.wallet||0))*12;if(c.id==='sbi-cashback')t-=((s.rent||0)+(s.wallet||0)+(s.fuel||0)+(s.utilities||0))*12;return Math.max(0,t)}
function fee(c,s){const f=c.fees||{};return !f.annual?0:(f.waiverThreshold&&eligible(c,s)>=f.waiverThreshold?0:f.annual*(f.gst?1+GST:1))}
function reward(c,s){const r=c.rewards||{};let v=0;
if(c.id==='sbi-cashback'){const on=Math.min(s.online||0,(r.monthlyOnlineCap||Infinity)/r.online);v+=on*r.online+Math.max(0,(s.online||0)-on)*r.offline;v+=((s.other||0)+(s.dining||0)+(s.travel||0)+(s.upi||0))*r.offline}
else if(c.id==='airtel-axis'){v+=Math.min(s.airtel||0,(r.airtelCapMonthly||Infinity)/r.airtel)*r.airtel;v+=Math.min(s.utilities||0,(r.utilitiesCapMonthly||Infinity)/r.utilitiesAirtelApp)*r.utilitiesAirtelApp;v+=Math.min((s.dining||0)+(s.online||0),(r.preferredCapMonthly||Infinity)/r.preferredApps)*r.preferredApps;v+=((s.other||0)+(s.travel||0)+(s.fuel||0)+(s.upi||0))*r.other}
else if(c.id==='axis-cashback')v+=((s.online||0)+(s.other||0)+(s.dining||0)+(s.travel||0)+(s.upi||0)+(s.airtel||0))*r.defaultCashback;
else if(c.id==='hdfc-millennia'){const preferred=Math.min((s.online||0),(r.onlinePreferredCap||Infinity));v+=preferred*r.onlinePreferred;v+=(Math.max(0,(s.online||0)-preferred)+(s.other||0)+(s.dining||0)+(s.travel||0)+(s.airtel||0)+(s.upi||0))*r.defaultCashback}
else if(c.id==='amazon-pay-icici')v+=(s.online||0)*r.amazonPrime+((s.other||0)+(s.dining||0)+(s.travel||0)+(s.airtel||0)+(s.upi||0))*r.other;
else if(c.id==='axis-ace')v+=(s.utilities||0)*r.utilityGpay+(s.dining||0)*r.dining+(s.online||0)*r.online+((s.other||0)+(s.travel||0)+(s.airtel||0)+(s.upi||0))*r.defaultCashback;
else if(c.id==='idfc-first-millennia'){const online=Math.max(0,s.online||0),base=Math.min(online,r.onlineThreshold||20000),inc=Math.max(0,online-base);v+=base*r.onlineBase+inc*r.onlineIncremental;v+=((s.other||0)+(s.dining||0)+(s.travel||0)+(s.airtel||0)+(s.upi||0))*r.offline}
return v*12}
function value(c,s){return {card:c,reward:reward(c,s),fee:fee(c,s),net:reward(c,s)-fee(c,s)}}
function combos(a,max){const out=[];function w(i,p){if(p.length)out.push(p.slice());if(p.length===max)return;for(;i<a.length;i++){p.push(a[i]);w(i+1,p);p.pop()}}w(0,[]);return out}
function wallet(cs,s){let rr=0,ff=0;const alloc={};for(const [k,v] of Object.entries(s)){let best=cs[0],bv=-1;for(const c of cs){const x={};x[k]=v;const q=reward(c,x);if(q>bv){bv=q;best=c}}(alloc[best.id]??={})[k]=v}for(const c of cs){const x=alloc[c.id]||{};rr+=reward(c,x);ff+=fee(c,x)}return {reward:rr,fee:ff,net:rr-ff,alloc}}
window.maxcredEvaluate=s=>{const cards=C.filter(c=>c.recommendationReady),all=combos(cards,3);let best=null;for(const cs of all){const v=wallet(cs,s);if(!best||v.net>best.net)best={...v,cards:cs}}return best};
window.optimize=function(){try{const s=spend(),names=[...document.querySelectorAll('.choice.selected strong')].map(x=>x.textContent.trim()),cur=C.filter(c=>names.includes(c.name)),current=cur.length?wallet(cur,s):{net:0,reward:0,fee:0},best=maxcredEvaluate(s),gain=Math.max(0,best.net-current.net);document.getElementById('current').textContent=m(current.net);document.getElementById('optimized').textContent=m(best.net);document.getElementById('gain').textContent='+'+m(gain);const rec=document.querySelector('.result .recs');if(rec)rec.innerHTML=best.cards.map((c,i)=>{const e=value(c,s),fit=Math.min(99,Math.max(65,Math.round(65+34*e.net/Math.max(1,best.net))));return `<div class="rec"><div class="role">${i?'Accelerator':'Primary'}</div><h3>${c.name}</h3><div class="reason">${c.note}</div><div class="score">Net annual value · ${m(e.net)}</div><div class="bar"><i style="width:${fit}%"></i></div><div class="reason" style="margin-top:10px">Effective annual fee: ${m(e.fee)} · Verified ${c.verifiedDate}</div></div>`}).join('');const n=document.querySelector('.notice');if(n)n.innerHTML='<b>MaxCred analysis:</b> '+best.cards.length+'-card wallet selected from '+C.filter(c=>c.recommendationReady).length+' verified cards. Categories are allocated to the strongest available reward economics and annual fee/waiver rules are applied.';document.getElementById('results').classList.add('show');document.getElementById('results').scrollIntoView({behavior:'smooth'})}catch(e){console.error('MaxCred analysis failed',e);const n=document.querySelector('.notice');if(n){n.textContent='Analysis could not be completed. Please refresh and try again.';n.style.display='block'}}};})();
